spring:
  flyway:
    enabled: true
    schemas: mentoring
  jpa:
    properties:
      hibernate:
        default_schema: mentoring

datasource:
  mentoring:
    pool-name: mentoring
    jdbc-url: jdbc:postgresql://localhost:5432/mentoring
    username: admin_db
    password: admin_db
    driver-class-name: org.postgresql.Driver

